<a href="https://colab.research.google.com/github/Shashwat-gla/Python_Assignment/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
## One of the liberary in Python
## Numirical Python

In [ ]:
import numpy as np

In [ ]:
# create a 1D array
marks=np.array([67, 87 ,88, 78 ,76 , 75])
print("Marks:",marks)
print("Type",type(marks))

Marks: [67 87 88 78 76 75]
Type <class 'numpy.ndarray'>


In [38]:
import numpy as np

# Create 2D array
marks = np.array([
    [45, 67, 87 ,66],
    [76, 87, 98 ,78],
    [67, 89, 75,77]
])

print(marks)

[[45 67 87 66]
 [76 87 98 78]
 [67 89 75 77]]


# 3D Array
## 2D
## 2D
## 2D
## consolidating this to from 3D array
Table 1
10 20 30
40 50 60

table 2:
70 80 90
100 110 120

Table 3:
130 140 150
160 170 180

In [ ]:
# 3D array
arr3 = np.array([
    [[10, 20, 30], [40, 50, 60]],
    [[70, 80, 90], [100, 110, 120]],
    [[130, 140, 150], [160, 170, 180]]
])

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]

 [[130 140 150]
  [160 170 180]]]
3


In [ ]:
# create array containing with zeros
arr4=np.zeros((3,4))
print(arr4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# np arange
arr5=np.arange(1,11)
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# np arrange with step increment
a6=np.arange(2,11,3)
print(a6)

[2 5 8]


In [ ]:
#random function
arr7=np.random.randint((2,3))
print(arr7)

[1 1]


In [ ]:
print(arr7.shape)
print(arr3.shape)
# Size Function represents no. of elements
print(arr3.size)
# prints n dimenssion
print(arr3.ndim)
# to find the data type of the array
print(marks.dtype)

(2,)
(3, 2, 3)
18
3
int64


In [37]:
#indexing
arr1=np.array([1,2,3,4,5])
print("Dimenssion is :",arr1.ndim)

# Create 2D array
marks = np.array([
    [45, 67, 87 ,66],
    [76, 87, 98 ,78],
    [67, 89, 75,77]
])
print(marks.shape)
print(marks.ndim)
print("Element in index 2 is :" , arr1[2])

# alicing
print(marks[0:2,1:3])

print(marks[0][2])
print(arr3[0][1][2])
#slicling
print(arr1[1:4])

Dimenssion is : 1
(3, 4)
2
Element in index 2 is : 3
87
60
[[67 87]
 [87 98]]
[2 3 4]
